global:
  resolve_timeout: 5m

route:
  receiver: 'slack-default' # default receiver

  routes:
    - match:
        severity: 'critical'
      receiver: 'slack-alerts-critical'

    - match:
        severity: 'high'
      receiver: 'slack-alerts-high'

    - match:
        severity: warning
      receiver: 'test-using'





receivers:
# inssert your url channels
  - name: 'slack-default'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxxxxxxxxx/yyyyyyyyyy/zzzzzzzzz'
        channel: '#alerts'
        send_resolved: true

  - name: 'slack-alerts-critical'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxxxxxxxxx/yyyyyyyyyy/zzzzzzzz'
        channel: '#alerts-critical'
        send_resolved: true

  - name: 'slack-alerts-high'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/xxxxxxxxxx/yyyyyyyyyy/zzzzzzzz'
        channel: '#alerts-high'
        send_resolved: true

  - name: 'test-using'
    slack_configs: 
      - api_url: 'https://hooks.slack.com/services/xxxxxxxxxx/yyyyyyyyyy/zzzzzzzz'
        channel: '#teat-using'
        send_resolved: true
