global:
  resolve_timeout: 5m

route:
  receiver: 'slack-default' # default receiver

  routes:
    - match:
        severity: 'critical'
      receiver: 'slack-alerts-critical'

    - match:
        severity: 'high'
      receiver: 'slack-alerts-high'

    - match:
        severity: warning
      receiver: 'test-using'





receivers:
  - name: 'slack-default'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts'
        send_resolved: true

  - name: 'slack-alerts-critical'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts-critical'
        send_resolved: true

  - name: 'slack-alerts-high'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#alerts-high'
        send_resolved: true

  - name: 'test-using'
    slack_configs: 
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#teat-using'
        send_resolved: true