groups:
- name: custome_rules
  rules:
    - record: node_memory_MemFree_percent
      expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

- name: alerts
  rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Instance [{{ $labels.instance }}] is down"
        description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minutes."

    - alert: BTCIsDown
      expr: up{instance="btc_app:8000"} == 0
      for: 1m
      labels:
        severity: high
      annotations:
        summary: "Instance [{{ $labels.instance }}] is down - High"
        description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minutes - High."

    - alert: LowCPUUsage
      expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)) < 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Instance [{{ $labels.instance }}] has low CPU usage"
        description: "CPU usage for instance [{{ $labels.instance }}] is below 50% for more than 1 minute."

