server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  ###### for mac #####
  - job_name: system
    static_configs:
       - targets:
           - localhost
         labels:
           job: varlogs
           __path__: /var/log/*log

  - job_name: btc_app
    static_configs:
      - targets:
          - localhost
        labels:
          job: btc_app
          __path__: /btc_app/btc_val.log

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_errors
          __path__: /nginx/log/error.log
